# General settings
# ----------------------------------------------------------------------------
# Number windows starting at 1
set -g base-index 1
# Number panes starting at 1
setw -g pane-base-index 1
# Faster ESC detection
set -sg escape-time 10

# Better copy mode with system clipboard
setw -g mode-keys vi
# Note: Requires xclip
bind -T copy-mode-vi y send-keys -X copy-pipe-and-c "xclip -selection clipboard -in"

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"

# Panel navigation shortcuts are set through tmux-pain-protocol
# Moving between panes: Prefix + h or C-h, etc
# Resizing panes: Prefix + H, etc


# Plugins
# ----------------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
# Sensible has the following settings by default:
# set -s escape-time 0
# set -g history-limit 50000
# set -g display-time 4000
# set -g status-interval 5
# set -g default-command "reattach-to-user-namespace -l $SHELL"
# set -g default-terminal "screen-256color"
# set -g status-keys emacs
# set -g focus-events on
# setw -g aggressive-resize on
# set -g @plugin 'tmux-plugins/tmux-sensible'
# bind C-p previous-window
# bind C-n next-window
# bind R source-file '~/.tmux.conf'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TPM (Needs to be at the very bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run-shell ~/.tmux/plugins/tmux-ressurect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux

